### ISSUE TITLE
Compiling with Dallas 1820 sensor code

### ISSUE THREAD

**Issue by spanout** [softypit/esp32_mqtt_eq3#29]
Has anyone tried to add a simple Dallas DS1820 temperature read into the app_main on eq3_main.c.  I would like to report back to mqtt the current room temperature as I do on a PiZero version of this, but I cannot seem to compile the code. I am a novice with this kind of thing. Would anyone else be interested in such a feature?

**Comment by Floyddotnet** [comment]
Take a look at this commit: https://github.com/buddebej/esp32_mqtt_eq3/commit/b645fb4861fbdd2497e7c28fdd695d08a360776a (Add support for dht22)

**Comment by spanout** [comment]
Thanks
