### ISSUE TITLE
documentation about pairing BLE missing

### ISSUE THREAD

**Issue by wkraft-fablabka** [softypit/esp32_mqtt_eq3#32]
I can't find any information how the BLE pairing works here.
When using the calor-BT-App you need to press the button on the eq3-valve, until PAIr followed by a 4digit code is shown on the valve. This code has to be entered in the app.

Where/How do I enter/configure the pairing code here?

[Example of the pairing process (german) ](https://www.smarthelpers.de/smarthome/eq-3-bluetooth-smart-heizkorperthermostat-im-praxistest.html)

**Comment by Floyddotnet** [comment]
The pairing process is a fake and not needed.

**Comment by wkraft-fablabka** [comment]
As i have now received my eq3, i can confirm, that the so called "pairing" is indeed fake. So I close this issue.
