### ISSUE TITLE
Undocumented Wifi and no HTML

### ISSUE THREAD

**Issue by Bonscha** [softypit/esp32_mqtt_eq3#69]
Hi,

I just flashed these images on Windows 11 - via ESP32 download tool v3.9.2 and having the proper driver installed - onto an ESP32-WROOM-32 that I had lying around.

I get a Wifi called "ESP_CC1995" instead of the documented Wifi name. Also it doesn't require a password. When connected, I don't get any HTML page under "192.168.4.1".

What could be the problem?

**Comment by softypit** [comment]
My guess is that the download didn't succeed. The AP name looks like a default that would be used by many applications (but not esp32_mqtt_eq3). 
You should be able to confirm this by looking at the serial output when the device boots.

**Comment by Bonscha** [comment]
Hi, great to hear from you so quickly! I have checked that yesterday, but didn't copy the serial output. It seemed there was no bootloader found, so the ESP32 couldn't even boot.

I erased via download tool, then flashed all 4 .img files on the respective memory adresses as indicated by the console script - but via Win GUI. Did that several times with two different and new devices - and didn't even get a Wifi AP anymore.

Does this even work with a ESP32-WROOM-32? I don't really find any other version and I'm not too familiar with the product family and potential differences in memory/firmware compatibility. If another variant is needed, I'll order that...

**Comment by Bonscha** [comment]
Here is the serial output, which loops with a high frequency:

`rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57
`

**Comment by softypit** [comment]
That definitely looks like a programming issue. I use ESP32-WROOM-32s with this application so it should work with yours.
I don't run windows so have not used the ESP32 download tool.
Are you able to try with the python tool (esptool.py)? If you can run that it should work with the flash command in the readme.

**Comment by Bonscha** [comment]
Seems that I'm not able to install esptool.py in my python 3.10 installation on Win 11.

```
>>> import os
>>> os.getcwd()
'C:\\Users\\sebas\\AppData\\Local\\Programs\\Python\\Python310'
>>> os.chdir("D:\Bonscha\Downloads\esptool-3.3")
>>> os.getcwd()
'D:\\Bonscha\\Downloads\\esptool-3.3'
>>> python setup.py install
  File "<stdin>", line 1
    python setup.py install
           ^^^^^
SyntaxError: invalid syntax
```

Installation from app repo fails with the same error.

**Comment by softypit** [comment]
I'm not sure what else to suggest. 
There's https://github.com/hanhdt/esp32-flash-tool which could be worth a try. Otherwise if you have a raspberry pi you could use that as a programmer with the linux tools.

**Comment by Bonscha** [comment]
Should have checked these boxes in ESP32 Download Tool before flashing, I guess...
I could facepalm myself all day long!

![image](https://user-images.githubusercontent.com/92258523/163559760-57720e20-122b-4876-b863-18ef3fe8d5ed.png)

Works now! Sorry to have bothered you! :(
